# Section1: Course introduction

# Section2: Environment set-up

## 1. Download Anaconda

## 2. Run in cmd: jupyter notebook

## 3. Conda command: 

- Tạo 1 môi trường ảo với tên env_name:

conda create -n env_name [python=3.6] [numpy] [pandas] [anaconda]

- Thêm một package vào virtualenv:

conda install -n env_name [ten-package]

- Kích hoạt env:

source activate env_name

- Deactivate env:

source deactivate

- Nếu đã activate môi trường thì cài package chỉ cần:

conda install [ten-package]

- Có thể cài package pip trên env để tiện install:

In [ ]:
conda install pip

- Sau khi cài pip có thể install package bằng pip:

In [ ]:
pip install [ten_package]

- Creating an environment file manually to share env for everyone in project:
Create file environment.yml, ex:


In [ ]:
name: myenv
dependencies:
  - python=3.6   # or 2.7
  - bokeh=0.9.2
  - numpy=1.9.*
  - nodejs=0.10.*
  - flask
  - pip:
    - Flask-Testing


- Chạy lệnh sau để tạo môi trường theo file environment.yml đã có sẵn:

In [ ]:
conda env create -f environment.yml

- Xem list các pacakage trong env:

In [ ]:
conda list ten-package

- Export env ra file environment.yml:

In [ ]:
conda env export > environment.yml

- Xóa một env:

In [ ]:
conda remove --name myenv --all

# Section 3: Jupyter overview

# Section 4: Python crash course

# Section 5: Python for Data Analysis - NumPy

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
slice_of_arr = arr[0:5]

In [5]:
slice_of_arr

array([0, 1, 2, 3, 4])

Khi thay đổi slice_of_arr thì chính ở arr cũng bị thay đổi theo

In [6]:
slice_of_arr[:] = 10

In [7]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

Nếu muốn không cho tham chiếu tới arr thì ta cần tạo một copy_arr bằng arr.copy()

In [8]:
copy_arr = arr.copy()

In [9]:
copy_arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [10]:
copy_arr[:] = 100

In [12]:
copy_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [11]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [13]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Đây là cách truy cập vào một số phần tử của arr 2 chiều:

In [18]:
arr_2d[2:,:2] # dòng từ dòng 2 trở đi và cột từ đầu đến cột 1

array([[35, 40]])

In [19]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [20]:
arr = np.arange(1, 11)

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
boolen_arr = arr > 5

In [24]:
boolen_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
arr[arr<5]

array([1, 2, 3, 4])

In [27]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [28]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.exp(arr) # y = e^x, e ~ 2.718...

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])