In [13]:
dic = {'1' : 'value1', 2 : 'value2'}

In [14]:
print(dic)

{'1': 'value1', 2: 'value2'}


In [16]:
dic['1']

'value1'

In [21]:
(1 > 0) and (1 < 2)

True

In [22]:
dic.items()

dict_items([('1', 'value1'), (2, 'value2')])

In [27]:
dic.items()

dict_items([('1', 'value1'), (2, 'value2')])

In [29]:
for (a,b) in dic.items():
    print(a, b)

1 value1
2 value2


In [1]:
'dog' in 'you are dogs'

True

In [2]:
import numpy as np

In [3]:
np.array([1, 1])

array([1, 1])

In [5]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [6]:
list = [[1, 2], [3, 4]]

In [7]:
list


[[1, 2], [3, 4]]

In [9]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [12]:
zero_matrix = np.zeros(3)

In [13]:
print(zero_matrix)

[0. 0. 0.]


In [16]:
zero_matrix[0]

0.0

In [17]:
type(zero_matrix[0])

numpy.float64

In [18]:
type(zero_matrix)

numpy.ndarray

In [26]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr = 2 * (np.random.rand(3, 2) + 3)

In [37]:
arr

array([[6.44402956, 6.96654251],
       [6.19351452, 7.76262186],
       [6.30924994, 6.5636964 ]])

In [40]:
np.random.randint(1, 10, 10)

array([8, 2, 4, 9, 4, 7, 8, 3, 7, 5])

In [41]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [61]:
arr = np.arange(6)

In [62]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
arr2 = np.reshape(arr, (2, 3))

In [75]:
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
arr.max()

5

In [78]:
arr2.max()

5

Return index of max value

In [79]:
arr.argmax()

5

In [80]:
arr.shape


(6,)

In [81]:
type(arr.shape)

tuple

In [84]:
arr = np.random.randint(0, 10, 30)

In [89]:
arr2 = arr.reshape(5, 6)

In [90]:
arr.shape

(30,)

In [91]:
arr2.shape

(5, 6)

In [95]:
arr.dtype

dtype('int64')

In [ ]:
arr2.dty